<?php

return [
    'slug' => 'government-contractor',
    'name' => 'Kontraktor Pemerintah',
    'description' => 'Template penggajian untuk kontraktor dan vendor pemerintah. Kepatuhan penuh terhadap regulasi, termasuk THR dan semua komponen BPJS sesuai tarif resmi.',
    'industry_type' => 'government',
    'company_size' => 'large',
    'icon' => 'account_balance',
    'sort_order' => 50,
    'includes_bpjs' => true,
    'includes_pph21' => true,
    'includes_overtime' => true,
    'items' => [
        [
            'name' => 'Gaji Pokok',
            'code' => 'GAJI_POKOK',
            'type' => 'earning',
            'category' => 'basic',
            'value_type' => 'flat',
            'formula' => null,
            'default_amount' => 0,
            'is_taxable' => true,
            'is_fixed' => true,
            'is_prorated' => true,
            'prorate_basis' => 'calendar_days',
            'execution_order' => 10,
            'depends_on' => null,
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'Pendapatan Tetap',
            'sort_within_group' => 1,
            'description' => 'Gaji pokok bulanan karyawan',
            'help_text' => 'Diprorata berdasarkan hari kalender',
        ],
        [
            'name' => 'Tunjangan Jabatan',
            'code' => 'TUNJ_JABATAN',
            'type' => 'earning',
            'category' => 'earning',
            'value_type' => 'flat',
            'formula' => null,
            'default_amount' => 0,
            'is_taxable' => true,
            'is_fixed' => true,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 20,
            'depends_on' => null,
            'is_required' => false,
            'is_optional' => true,
            'group_label' => 'Pendapatan Tetap',
            'sort_within_group' => 2,
            'description' => 'Tunjangan berdasarkan jabatan/posisi',
            'help_text' => null,
        ],
        [
            'name' => 'Tunjangan Transport',
            'code' => 'TUNJ_TRANSPORT',
            'type' => 'earning',
            'category' => 'earning',
            'value_type' => 'flat',
            'formula' => null,
            'default_amount' => 0,
            'is_taxable' => true,
            'is_fixed' => true,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 30,
            'depends_on' => null,
            'is_required' => false,
            'is_optional' => false,
            'group_label' => 'Tunjangan',
            'sort_within_group' => 1,
            'description' => 'Tunjangan transportasi bulanan',
            'help_text' => null,
        ],
        [
            'name' => 'Tunjangan Makan',
            'code' => 'TUNJ_MAKAN',
            'type' => 'earning',
            'category' => 'earning',
            'value_type' => 'formula',
            'formula' => 'present_days * 30000',
            'default_amount' => 0,
            'is_taxable' => true,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 40,
            'depends_on' => ['present_days'],
            'is_required' => false,
            'is_optional' => false,
            'group_label' => 'Tunjangan',
            'sort_within_group' => 2,
            'description' => 'Tunjangan makan berdasarkan hari kehadiran',
            'help_text' => 'Rp 30.000 per hari hadir',
        ],
        [
            'name' => 'Tunjangan Kehadiran',
            'code' => 'TUNJ_KEHADIRAN',
            'type' => 'earning',
            'category' => 'earning',
            'value_type' => 'formula',
            'formula' => 'if(absent_days == 0, 500000, 0)',
            'default_amount' => 0,
            'is_taxable' => true,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 50,
            'depends_on' => ['absent_days'],
            'is_required' => false,
            'is_optional' => true,
            'group_label' => 'Tunjangan',
            'sort_within_group' => 3,
            'description' => 'Bonus kehadiran penuh',
            'help_text' => 'Rp 500.000 jika tidak ada absen',
        ],
        [
            'name' => 'THR (Tunjangan Hari Raya)',
            'code' => 'THR',
            'type' => 'earning',
            'category' => 'earning',
            'value_type' => 'formula',
            'formula' => 'if(is_thr_month, if(months_worked >= 12, basic_salary, basic_salary * months_worked / 12), 0)',
            'default_amount' => 0,
            'is_taxable' => true,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 55,
            'depends_on' => ['is_thr_month', 'months_worked', 'basic_salary'],
            'is_required' => false,
            'is_optional' => true,
            'group_label' => 'Pendapatan Variabel',
            'sort_within_group' => 1,
            'description' => 'Tunjangan Hari Raya sesuai Permenaker',
            'help_text' => 'Proporsional jika masa kerja < 12 bulan. Dibayarkan H-7 hari raya keagamaan.',
        ],
        [
            'name' => 'Uang Lembur',
            'code' => 'UANG_LEMBUR',
            'type' => 'earning',
            'category' => 'earning',
            'value_type' => 'formula',
            'formula' => 'overtime_hours * (basic_salary / 173) * 1.5',
            'default_amount' => 0,
            'is_taxable' => true,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 60,
            'depends_on' => ['overtime_hours', 'basic_salary'],
            'is_required' => false,
            'is_optional' => false,
            'group_label' => 'Pendapatan Variabel',
            'sort_within_group' => 2,
            'description' => 'Upah lembur sesuai PP 35/2021',
            'help_text' => 'Sesuai ketentuan PP 35 Tahun 2021',
        ],
        [
            'name' => 'Potongan Keterlambatan',
            'code' => 'POT_TERLAMBAT',
            'type' => 'deduction',
            'category' => 'deduction',
            'value_type' => 'formula',
            'formula' => 'late_count * 50000',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 70,
            'depends_on' => ['late_count'],
            'is_required' => false,
            'is_optional' => false,
            'group_label' => 'Potongan',
            'sort_within_group' => 1,
            'description' => 'Potongan per kejadian terlambat',
            'help_text' => 'Rp 50.000 per keterlambatan',
        ],
        [
            'name' => 'Potongan Cuti Tidak Dibayar',
            'code' => 'POT_CUTI_UNPAID',
            'type' => 'deduction',
            'category' => 'deduction',
            'value_type' => 'formula',
            'formula' => 'leave_days_unpaid * (basic_salary / working_days)',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 80,
            'depends_on' => ['leave_days_unpaid', 'basic_salary', 'working_days'],
            'is_required' => false,
            'is_optional' => false,
            'group_label' => 'Potongan',
            'sort_within_group' => 2,
            'description' => 'Potongan untuk cuti tanpa gaji',
            'help_text' => null,
        ],
        [
            'name' => 'BPJS Kesehatan (Karyawan)',
            'code' => 'BPJS_KES_EMP',
            'type' => 'deduction',
            'category' => 'bpjs_employee',
            'value_type' => 'formula',
            'formula' => 'min(gross_salary, 12000000) * 0.01',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 100,
            'depends_on' => ['gross_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Karyawan',
            'sort_within_group' => 1,
            'description' => 'Iuran BPJS Kesehatan bagian karyawan (1%)',
            'help_text' => 'Sesuai Perpres 64/2020',
        ],
        [
            'name' => 'BPJS JHT (Karyawan)',
            'code' => 'BPJS_JHT_EMP',
            'type' => 'deduction',
            'category' => 'bpjs_employee',
            'value_type' => 'formula',
            'formula' => 'basic_salary * 0.02',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 110,
            'depends_on' => ['basic_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Karyawan',
            'sort_within_group' => 2,
            'description' => 'Iuran Jaminan Hari Tua bagian karyawan (2%)',
            'help_text' => 'Sesuai PP 46/2015',
        ],
        [
            'name' => 'BPJS JP (Karyawan)',
            'code' => 'BPJS_JP_EMP',
            'type' => 'deduction',
            'category' => 'bpjs_employee',
            'value_type' => 'formula',
            'formula' => 'min(basic_salary, 10042300) * 0.01',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 120,
            'depends_on' => ['basic_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Karyawan',
            'sort_within_group' => 3,
            'description' => 'Iuran Jaminan Pensiun bagian karyawan (1%)',
            'help_text' => 'Batas atas gaji Rp 10.042.300',
        ],
        [
            'name' => 'BPJS Kesehatan (Perusahaan)',
            'code' => 'BPJS_KES_COMP',
            'type' => 'benefit',
            'category' => 'bpjs_company',
            'value_type' => 'formula',
            'formula' => 'min(gross_salary, 12000000) * 0.04',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 130,
            'depends_on' => ['gross_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Perusahaan',
            'sort_within_group' => 1,
            'description' => 'Iuran BPJS Kesehatan bagian perusahaan (4%)',
            'help_text' => null,
        ],
        [
            'name' => 'BPJS JHT (Perusahaan)',
            'code' => 'BPJS_JHT_COMP',
            'type' => 'benefit',
            'category' => 'bpjs_company',
            'value_type' => 'formula',
            'formula' => 'basic_salary * 0.037',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 140,
            'depends_on' => ['basic_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Perusahaan',
            'sort_within_group' => 2,
            'description' => 'Iuran Jaminan Hari Tua bagian perusahaan (3.7%)',
            'help_text' => null,
        ],
        [
            'name' => 'BPJS JKK (Perusahaan)',
            'code' => 'BPJS_JKK_COMP',
            'type' => 'benefit',
            'category' => 'bpjs_company',
            'value_type' => 'formula',
            'formula' => 'basic_salary * 0.0024',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 150,
            'depends_on' => ['basic_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Perusahaan',
            'sort_within_group' => 3,
            'description' => 'Iuran Jaminan Kecelakaan Kerja (0.24%)',
            'help_text' => 'Rate Kelompok I — sesuaikan jika bidang usaha berbeda',
        ],
        [
            'name' => 'BPJS JKM (Perusahaan)',
            'code' => 'BPJS_JKM_COMP',
            'type' => 'benefit',
            'category' => 'bpjs_company',
            'value_type' => 'formula',
            'formula' => 'basic_salary * 0.003',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 160,
            'depends_on' => ['basic_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Perusahaan',
            'sort_within_group' => 4,
            'description' => 'Iuran Jaminan Kematian (0.3%)',
            'help_text' => null,
        ],
        [
            'name' => 'BPJS JP (Perusahaan)',
            'code' => 'BPJS_JP_COMP',
            'type' => 'benefit',
            'category' => 'bpjs_company',
            'value_type' => 'formula',
            'formula' => 'min(basic_salary, 10042300) * 0.02',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 170,
            'depends_on' => ['basic_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Perusahaan',
            'sort_within_group' => 5,
            'description' => 'Iuran Jaminan Pensiun bagian perusahaan (2%)',
            'help_text' => 'Batas atas gaji Rp 10.042.300',
        ],
        [
            'name' => 'PPh 21 (TER)',
            'code' => 'PPH21_TER',
            'type' => 'deduction',
            'category' => 'tax',
            'value_type' => 'formula',
            'formula' => 'gross_salary * ter_rate',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 200,
            'depends_on' => ['gross_salary', 'ter_rate'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'Pajak',
            'sort_within_group' => 1,
            'description' => 'Pajak Penghasilan Pasal 21 metode TER',
            'help_text' => 'Sesuai PP 58/2023 dan PMK 168/2023',
        ],
    ],
];
