<?php

return [
    'slug' => 'manufacturing-full',
    'name' => 'Manufaktur Lengkap',
    'description' => 'Template penggajian lengkap untuk industri manufaktur. Termasuk tunjangan shift, risiko kerja, lembur malam, dan BPJS dengan rate JKK Kelompok III.',
    'industry_type' => 'manufacturing',
    'company_size' => 'medium',
    'icon' => 'precision_manufacturing',
    'sort_order' => 20,
    'includes_bpjs' => true,
    'includes_pph21' => true,
    'includes_overtime' => true,
    'items' => [
        [
            'name' => 'Gaji Pokok',
            'code' => 'GAJI_POKOK',
            'type' => 'earning',
            'category' => 'basic',
            'value_type' => 'flat',
            'formula' => null,
            'default_amount' => 0,
            'is_taxable' => true,
            'is_fixed' => true,
            'is_prorated' => true,
            'prorate_basis' => 'working_days',
            'execution_order' => 10,
            'depends_on' => null,
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'Pendapatan Tetap',
            'sort_within_group' => 1,
            'description' => 'Gaji pokok bulanan karyawan',
            'help_text' => 'Diprorata berdasarkan hari kerja',
        ],
        [
            'name' => 'Tunjangan Jabatan',
            'code' => 'TUNJ_JABATAN',
            'type' => 'earning',
            'category' => 'earning',
            'value_type' => 'flat',
            'formula' => null,
            'default_amount' => 0,
            'is_taxable' => true,
            'is_fixed' => true,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 20,
            'depends_on' => null,
            'is_required' => false,
            'is_optional' => true,
            'group_label' => 'Pendapatan Tetap',
            'sort_within_group' => 2,
            'description' => 'Tunjangan berdasarkan jabatan/posisi',
            'help_text' => null,
        ],
        [
            'name' => 'Tunjangan Transport',
            'code' => 'TUNJ_TRANSPORT',
            'type' => 'earning',
            'category' => 'earning',
            'value_type' => 'flat',
            'formula' => null,
            'default_amount' => 0,
            'is_taxable' => true,
            'is_fixed' => true,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 30,
            'depends_on' => null,
            'is_required' => false,
            'is_optional' => false,
            'group_label' => 'Tunjangan',
            'sort_within_group' => 1,
            'description' => 'Tunjangan transportasi bulanan',
            'help_text' => null,
        ],
        [
            'name' => 'Tunjangan Makan',
            'code' => 'TUNJ_MAKAN',
            'type' => 'earning',
            'category' => 'earning',
            'value_type' => 'formula',
            'formula' => 'present_days * 25000',
            'default_amount' => 0,
            'is_taxable' => true,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 40,
            'depends_on' => ['present_days'],
            'is_required' => false,
            'is_optional' => false,
            'group_label' => 'Tunjangan',
            'sort_within_group' => 2,
            'description' => 'Tunjangan makan berdasarkan hari kehadiran',
            'help_text' => 'Rp 25.000 per hari hadir',
        ],
        [
            'name' => 'Tunjangan Shift',
            'code' => 'TUNJ_SHIFT',
            'type' => 'earning',
            'category' => 'earning',
            'value_type' => 'flat',
            'formula' => null,
            'default_amount' => 300000,
            'is_taxable' => true,
            'is_fixed' => true,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 45,
            'depends_on' => null,
            'is_required' => false,
            'is_optional' => false,
            'group_label' => 'Tunjangan',
            'sort_within_group' => 3,
            'description' => 'Tunjangan untuk karyawan yang bekerja shift',
            'help_text' => 'Berlaku untuk shift 2 dan shift 3',
        ],
        [
            'name' => 'Tunjangan Risiko',
            'code' => 'TUNJ_RISIKO',
            'type' => 'earning',
            'category' => 'earning',
            'value_type' => 'flat',
            'formula' => null,
            'default_amount' => 200000,
            'is_taxable' => true,
            'is_fixed' => true,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 46,
            'depends_on' => null,
            'is_required' => false,
            'is_optional' => false,
            'group_label' => 'Tunjangan',
            'sort_within_group' => 4,
            'description' => 'Tunjangan risiko kerja untuk area produksi',
            'help_text' => 'Untuk karyawan di area produksi/gudang',
        ],
        [
            'name' => 'Tunjangan Kehadiran',
            'code' => 'TUNJ_KEHADIRAN',
            'type' => 'earning',
            'category' => 'earning',
            'value_type' => 'formula',
            'formula' => 'if(absent_days == 0, 500000, 0)',
            'default_amount' => 0,
            'is_taxable' => true,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 50,
            'depends_on' => ['absent_days'],
            'is_required' => false,
            'is_optional' => true,
            'group_label' => 'Tunjangan',
            'sort_within_group' => 5,
            'description' => 'Bonus kehadiran penuh',
            'help_text' => 'Rp 500.000 jika tidak ada absen',
        ],
        [
            'name' => 'Uang Lembur',
            'code' => 'UANG_LEMBUR',
            'type' => 'earning',
            'category' => 'earning',
            'value_type' => 'formula',
            'formula' => 'overtime_hours * (basic_salary / 173) * 1.5',
            'default_amount' => 0,
            'is_taxable' => true,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 60,
            'depends_on' => ['overtime_hours', 'basic_salary'],
            'is_required' => false,
            'is_optional' => false,
            'group_label' => 'Pendapatan Variabel',
            'sort_within_group' => 1,
            'description' => 'Upah lembur sesuai UU Ketenagakerjaan',
            'help_text' => 'Dihitung: jam lembur × (gaji pokok / 173) × 1.5',
        ],
        [
            'name' => 'Tunjangan Lembur Malam',
            'code' => 'TUNJ_MALAM',
            'type' => 'earning',
            'category' => 'earning',
            'value_type' => 'formula',
            'formula' => 'night_shift_days * 50000',
            'default_amount' => 0,
            'is_taxable' => true,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 65,
            'depends_on' => ['night_shift_days'],
            'is_required' => false,
            'is_optional' => false,
            'group_label' => 'Pendapatan Variabel',
            'sort_within_group' => 2,
            'description' => 'Tunjangan tambahan untuk shift malam',
            'help_text' => 'Rp 50.000 per hari shift malam',
        ],
        [
            'name' => 'Potongan Keterlambatan',
            'code' => 'POT_TERLAMBAT',
            'type' => 'deduction',
            'category' => 'deduction',
            'value_type' => 'formula',
            'formula' => 'late_count * 50000',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 70,
            'depends_on' => ['late_count'],
            'is_required' => false,
            'is_optional' => false,
            'group_label' => 'Potongan',
            'sort_within_group' => 1,
            'description' => 'Potongan per kejadian terlambat',
            'help_text' => 'Rp 50.000 per keterlambatan',
        ],
        [
            'name' => 'Potongan Cuti Tidak Dibayar',
            'code' => 'POT_CUTI_UNPAID',
            'type' => 'deduction',
            'category' => 'deduction',
            'value_type' => 'formula',
            'formula' => 'leave_days_unpaid * (basic_salary / working_days)',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 80,
            'depends_on' => ['leave_days_unpaid', 'basic_salary', 'working_days'],
            'is_required' => false,
            'is_optional' => false,
            'group_label' => 'Potongan',
            'sort_within_group' => 2,
            'description' => 'Potongan untuk cuti tanpa gaji',
            'help_text' => null,
        ],
        [
            'name' => 'BPJS Kesehatan (Karyawan)',
            'code' => 'BPJS_KES_EMP',
            'type' => 'deduction',
            'category' => 'bpjs_employee',
            'value_type' => 'formula',
            'formula' => 'min(gross_salary, 12000000) * 0.01',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 100,
            'depends_on' => ['gross_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Karyawan',
            'sort_within_group' => 1,
            'description' => 'Iuran BPJS Kesehatan bagian karyawan (1%)',
            'help_text' => 'Batas atas gaji Rp 12.000.000',
        ],
        [
            'name' => 'BPJS JHT (Karyawan)',
            'code' => 'BPJS_JHT_EMP',
            'type' => 'deduction',
            'category' => 'bpjs_employee',
            'value_type' => 'formula',
            'formula' => 'basic_salary * 0.02',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 110,
            'depends_on' => ['basic_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Karyawan',
            'sort_within_group' => 2,
            'description' => 'Iuran Jaminan Hari Tua bagian karyawan (2%)',
            'help_text' => null,
        ],
        [
            'name' => 'BPJS JP (Karyawan)',
            'code' => 'BPJS_JP_EMP',
            'type' => 'deduction',
            'category' => 'bpjs_employee',
            'value_type' => 'formula',
            'formula' => 'min(basic_salary, 10042300) * 0.01',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 120,
            'depends_on' => ['basic_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Karyawan',
            'sort_within_group' => 3,
            'description' => 'Iuran Jaminan Pensiun bagian karyawan (1%)',
            'help_text' => 'Batas atas gaji Rp 10.042.300',
        ],
        [
            'name' => 'BPJS Kesehatan (Perusahaan)',
            'code' => 'BPJS_KES_COMP',
            'type' => 'benefit',
            'category' => 'bpjs_company',
            'value_type' => 'formula',
            'formula' => 'min(gross_salary, 12000000) * 0.04',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 130,
            'depends_on' => ['gross_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Perusahaan',
            'sort_within_group' => 1,
            'description' => 'Iuran BPJS Kesehatan bagian perusahaan (4%)',
            'help_text' => null,
        ],
        [
            'name' => 'BPJS JHT (Perusahaan)',
            'code' => 'BPJS_JHT_COMP',
            'type' => 'benefit',
            'category' => 'bpjs_company',
            'value_type' => 'formula',
            'formula' => 'basic_salary * 0.037',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 140,
            'depends_on' => ['basic_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Perusahaan',
            'sort_within_group' => 2,
            'description' => 'Iuran Jaminan Hari Tua bagian perusahaan (3.7%)',
            'help_text' => null,
        ],
        [
            'name' => 'BPJS JKK (Perusahaan)',
            'code' => 'BPJS_JKK_COMP',
            'type' => 'benefit',
            'category' => 'bpjs_company',
            'value_type' => 'formula',
            'formula' => 'basic_salary * 0.0089',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 150,
            'depends_on' => ['basic_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Perusahaan',
            'sort_within_group' => 3,
            'description' => 'Iuran Jaminan Kecelakaan Kerja (0.89%)',
            'help_text' => 'Rate Kelompok III (risiko sedang)',
        ],
        [
            'name' => 'BPJS JKM (Perusahaan)',
            'code' => 'BPJS_JKM_COMP',
            'type' => 'benefit',
            'category' => 'bpjs_company',
            'value_type' => 'formula',
            'formula' => 'basic_salary * 0.003',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 160,
            'depends_on' => ['basic_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Perusahaan',
            'sort_within_group' => 4,
            'description' => 'Iuran Jaminan Kematian (0.3%)',
            'help_text' => null,
        ],
        [
            'name' => 'BPJS JP (Perusahaan)',
            'code' => 'BPJS_JP_COMP',
            'type' => 'benefit',
            'category' => 'bpjs_company',
            'value_type' => 'formula',
            'formula' => 'min(basic_salary, 10042300) * 0.02',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 170,
            'depends_on' => ['basic_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Perusahaan',
            'sort_within_group' => 5,
            'description' => 'Iuran Jaminan Pensiun bagian perusahaan (2%)',
            'help_text' => 'Batas atas gaji Rp 10.042.300',
        ],
        [
            'name' => 'PPh 21 (TER)',
            'code' => 'PPH21_TER',
            'type' => 'deduction',
            'category' => 'tax',
            'value_type' => 'formula',
            'formula' => 'gross_salary * ter_rate',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 200,
            'depends_on' => ['gross_salary', 'ter_rate'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'Pajak',
            'sort_within_group' => 1,
            'description' => 'Pajak Penghasilan Pasal 21 metode TER',
            'help_text' => 'Tarif Efektif Rata-rata sesuai PP 58/2023',
        ],
    ],
];
