<?php

return [
    'slug' => 'retail-basic',
    'name' => 'Retail Basic',
    'description' => 'Template penggajian sederhana untuk bisnis retail dan F&B. Komponen minimal dengan service charge dan tanpa tunjangan jabatan.',
    'industry_type' => 'retail',
    'company_size' => 'small',
    'icon' => 'storefront',
    'sort_order' => 30,
    'includes_bpjs' => true,
    'includes_pph21' => true,
    'includes_overtime' => true,
    'items' => [
        [
            'name' => 'Gaji Pokok',
            'code' => 'GAJI_POKOK',
            'type' => 'earning',
            'category' => 'basic',
            'value_type' => 'flat',
            'formula' => null,
            'default_amount' => 0,
            'is_taxable' => true,
            'is_fixed' => true,
            'is_prorated' => true,
            'prorate_basis' => 'working_days',
            'execution_order' => 10,
            'depends_on' => null,
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'Pendapatan Tetap',
            'sort_within_group' => 1,
            'description' => 'Gaji pokok bulanan karyawan',
            'help_text' => 'Diprorata berdasarkan hari kerja',
        ],
        [
            'name' => 'Tunjangan Transport',
            'code' => 'TUNJ_TRANSPORT',
            'type' => 'earning',
            'category' => 'earning',
            'value_type' => 'flat',
            'formula' => null,
            'default_amount' => 0,
            'is_taxable' => true,
            'is_fixed' => true,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 30,
            'depends_on' => null,
            'is_required' => false,
            'is_optional' => false,
            'group_label' => 'Tunjangan',
            'sort_within_group' => 1,
            'description' => 'Tunjangan transportasi bulanan',
            'help_text' => null,
        ],
        [
            'name' => 'Tunjangan Makan',
            'code' => 'TUNJ_MAKAN',
            'type' => 'earning',
            'category' => 'earning',
            'value_type' => 'formula',
            'formula' => 'present_days * 20000',
            'default_amount' => 0,
            'is_taxable' => true,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 40,
            'depends_on' => ['present_days'],
            'is_required' => false,
            'is_optional' => false,
            'group_label' => 'Tunjangan',
            'sort_within_group' => 2,
            'description' => 'Tunjangan makan berdasarkan hari kehadiran',
            'help_text' => 'Rp 20.000 per hari hadir',
        ],
        [
            'name' => 'Service Charge',
            'code' => 'SERVICE_CHARGE',
            'type' => 'earning',
            'category' => 'earning',
            'value_type' => 'formula',
            'formula' => 'total_service_charge / total_employees',
            'default_amount' => 0,
            'is_taxable' => true,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 55,
            'depends_on' => ['total_service_charge', 'total_employees'],
            'is_required' => false,
            'is_optional' => true,
            'group_label' => 'Pendapatan Variabel',
            'sort_within_group' => 1,
            'description' => 'Pembagian service charge dari pelanggan',
            'help_text' => 'Dibagi rata ke seluruh karyawan aktif',
        ],
        [
            'name' => 'Uang Lembur',
            'code' => 'UANG_LEMBUR',
            'type' => 'earning',
            'category' => 'earning',
            'value_type' => 'formula',
            'formula' => 'overtime_hours * (basic_salary / 173) * 1.5',
            'default_amount' => 0,
            'is_taxable' => true,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 60,
            'depends_on' => ['overtime_hours', 'basic_salary'],
            'is_required' => false,
            'is_optional' => false,
            'group_label' => 'Pendapatan Variabel',
            'sort_within_group' => 2,
            'description' => 'Upah lembur sesuai UU Ketenagakerjaan',
            'help_text' => null,
        ],
        [
            'name' => 'Potongan Keterlambatan',
            'code' => 'POT_TERLAMBAT',
            'type' => 'deduction',
            'category' => 'deduction',
            'value_type' => 'formula',
            'formula' => 'late_count * 25000',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 70,
            'depends_on' => ['late_count'],
            'is_required' => false,
            'is_optional' => false,
            'group_label' => 'Potongan',
            'sort_within_group' => 1,
            'description' => 'Potongan per kejadian terlambat',
            'help_text' => 'Rp 25.000 per keterlambatan',
        ],
        [
            'name' => 'BPJS Kesehatan (Karyawan)',
            'code' => 'BPJS_KES_EMP',
            'type' => 'deduction',
            'category' => 'bpjs_employee',
            'value_type' => 'formula',
            'formula' => 'min(gross_salary, 12000000) * 0.01',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 100,
            'depends_on' => ['gross_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Karyawan',
            'sort_within_group' => 1,
            'description' => 'Iuran BPJS Kesehatan bagian karyawan (1%)',
            'help_text' => null,
        ],
        [
            'name' => 'BPJS JHT (Karyawan)',
            'code' => 'BPJS_JHT_EMP',
            'type' => 'deduction',
            'category' => 'bpjs_employee',
            'value_type' => 'formula',
            'formula' => 'basic_salary * 0.02',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 110,
            'depends_on' => ['basic_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Karyawan',
            'sort_within_group' => 2,
            'description' => 'Iuran Jaminan Hari Tua bagian karyawan (2%)',
            'help_text' => null,
        ],
        [
            'name' => 'BPJS JP (Karyawan)',
            'code' => 'BPJS_JP_EMP',
            'type' => 'deduction',
            'category' => 'bpjs_employee',
            'value_type' => 'formula',
            'formula' => 'min(basic_salary, 10042300) * 0.01',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 120,
            'depends_on' => ['basic_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Karyawan',
            'sort_within_group' => 3,
            'description' => 'Iuran Jaminan Pensiun bagian karyawan (1%)',
            'help_text' => null,
        ],
        [
            'name' => 'BPJS Kesehatan (Perusahaan)',
            'code' => 'BPJS_KES_COMP',
            'type' => 'benefit',
            'category' => 'bpjs_company',
            'value_type' => 'formula',
            'formula' => 'min(gross_salary, 12000000) * 0.04',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 130,
            'depends_on' => ['gross_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Perusahaan',
            'sort_within_group' => 1,
            'description' => 'Iuran BPJS Kesehatan bagian perusahaan (4%)',
            'help_text' => null,
        ],
        [
            'name' => 'BPJS JHT (Perusahaan)',
            'code' => 'BPJS_JHT_COMP',
            'type' => 'benefit',
            'category' => 'bpjs_company',
            'value_type' => 'formula',
            'formula' => 'basic_salary * 0.037',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 140,
            'depends_on' => ['basic_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Perusahaan',
            'sort_within_group' => 2,
            'description' => 'Iuran Jaminan Hari Tua bagian perusahaan (3.7%)',
            'help_text' => null,
        ],
        [
            'name' => 'BPJS JKK (Perusahaan)',
            'code' => 'BPJS_JKK_COMP',
            'type' => 'benefit',
            'category' => 'bpjs_company',
            'value_type' => 'formula',
            'formula' => 'basic_salary * 0.0024',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 150,
            'depends_on' => ['basic_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Perusahaan',
            'sort_within_group' => 3,
            'description' => 'Iuran Jaminan Kecelakaan Kerja (0.24%)',
            'help_text' => 'Rate Kelompok I',
        ],
        [
            'name' => 'BPJS JKM (Perusahaan)',
            'code' => 'BPJS_JKM_COMP',
            'type' => 'benefit',
            'category' => 'bpjs_company',
            'value_type' => 'formula',
            'formula' => 'basic_salary * 0.003',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 160,
            'depends_on' => ['basic_salary'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'BPJS Perusahaan',
            'sort_within_group' => 4,
            'description' => 'Iuran Jaminan Kematian (0.3%)',
            'help_text' => null,
        ],
        [
            'name' => 'PPh 21 (TER)',
            'code' => 'PPH21_TER',
            'type' => 'deduction',
            'category' => 'tax',
            'value_type' => 'formula',
            'formula' => 'gross_salary * ter_rate',
            'default_amount' => 0,
            'is_taxable' => false,
            'is_fixed' => false,
            'is_prorated' => false,
            'prorate_basis' => null,
            'execution_order' => 200,
            'depends_on' => ['gross_salary', 'ter_rate'],
            'is_required' => true,
            'is_optional' => false,
            'group_label' => 'Pajak',
            'sort_within_group' => 1,
            'description' => 'Pajak Penghasilan Pasal 21 metode TER',
            'help_text' => null,
        ],
    ],
];
